### ISSUE TITLE
Support for Unity LTS version 19.4

### ISSUE THREAD

**Issue by alexey-kruchenok** [Leopotam/ecs-unityintegration#3]

**Comment by Leopotam** [comment]
@alexey-kruchenok Any issues with 2019.4?

**Comment by alexey-kruchenok** [comment]
> @alexey-kruchenok Any issues with 2019.4?

Just need to update Unity version in manifest, in another case it won't install from git URL.

**Comment by Leopotam** [comment]
@alexey-kruchenok checked on 2019.4.8f1 and 2020.1.2f1 - no issues, even no warnings, then checked on . You should import `ecs` repo first, then `ecs-unityintegration` - it described at `README`. For using git-links you should install `git` at system level and be sure that it available through `PATH` environment variable.
